"""
All UI strings in English and Arabic.
Access via:  from utils.lang import tr
             tr('key')
"""

TRANSLATIONS = {
    # ── App / Main window ─────────────────────────────────────────────────────
    'app_title':            {'en': 'Louafi Soft - Point of Sale System',
                             'ar': 'لوعافي سوفت - نظام نقطة البيع'},
    'nav_dashboard':        {'en': 'Dashboard',    'ar': 'لوحة التحكم'},
    'nav_products':         {'en': 'Products',     'ar': 'المنتجات'},
    'nav_inventory':        {'en': 'Inventory',    'ar': 'المخزون'},
    'nav_reports':          {'en': 'Reports',      'ar': 'التقارير'},
    'nav_customers':        {'en': 'Customers',    'ar': 'العملاء'},
    'nav_suppliers':        {'en': 'Suppliers',    'ar': 'الموردون'},
    'btn_refresh':          {'en': 'Refresh',      'ar': 'تحديث'},
    'status_refreshed':     {'en': 'Data refreshed ✔', 'ar': 'تم التحديث ✔'},
    'lang_switch_to_ar':    {'en': 'العربية',      'ar': 'English'},

    # ── Dashboard ─────────────────────────────────────────────────────────────
    'search_placeholder':   {'en': '  Search by name or barcode…',
                             'ar': '  ابحث بالاسم أو الباركود…'},
    'search_results':       {'en': 'Search Results',   'ar': 'نتائج البحث'},
    'speed_sale':           {'en': ' Speed Sale',      'ar': ' البيع السريع'},
    'btn_manage':           {'en': ' Manage',          'ar': ' إدارة'},
    'cart':                 {'en': 'Cart',              'ar': 'سلة المشتريات'},
    'btn_clear_cart':       {'en': 'Clear Cart',        'ar': 'تفريغ السلة'},
    'col_id':               {'en': 'ID',               'ar': 'م'},
    'col_name':             {'en': 'Name',              'ar': 'الاسم'},
    'col_price':            {'en': 'Price',             'ar': 'السعر'},
    'col_qty':              {'en': 'Qty',               'ar': 'الكمية'},
    'col_total':            {'en': 'Total',             'ar': 'الإجمالي'},
    'col_actions':          {'en': 'Actions',           'ar': 'إجراءات'},
    'order_summary':        {'en': 'Order Summary',     'ar': 'ملخص الطلب'},
    'customer':             {'en': 'Customer',          'ar': 'العميل'},
    'walkin':               {'en': '— Walk-in / No customer —',
                             'ar': '— زيارة عادية —'},
    'total_label':          {'en': 'Total',             'ar': 'الإجمالي'},
    'btn_accept_sale':      {'en': ' Accept Sale',      'ar': ' قبول البيع'},
    'btn_save_debt':        {'en': ' Save as Debt',     'ar': ' حفظ كدَين'},
    'btn_delete':           {'en': 'Delete',            'ar': 'حذف'},
    'reload_customers':     {'en': 'Reload customer list', 'ar': 'إعادة تحميل العملاء'},
    'outstanding_debt':     {'en': 'Outstanding debt: ', 'ar': 'دين متبقٍ: '},
    'sale_complete':        {'en': 'Sale Complete',     'ar': 'تم البيع'},
    'sale_complete_msg':    {'en': 'Sale #{id}{cust} completed.\nTotal: {total:.2f}',
                             'ar': 'تم إتمام البيع #{id}{cust}.\nالإجمالي: {total:.2f}'},
    'error':                {'en': 'Error',             'ar': 'خطأ'},
    'no_customer':          {'en': 'No Customer',       'ar': 'لا يوجد عميل'},
    'no_customer_msg':      {'en': 'Please select a customer first.',
                             'ar': 'يرجى تحديد عميل أولاً.'},
    'empty_cart':           {'en': 'Empty Cart',        'ar': 'السلة فارغة'},
    'empty_cart_msg':       {'en': 'Cart is empty.',    'ar': 'السلة فارغة.'},
    'save_as_debt':         {'en': 'Save as Debt',      'ar': 'حفظ كدَين'},
    'save_debt_q':          {'en': 'Save total {total:.2f} as debt for {name}?\nCurrent balance: {bal:,.2f}',
                             'ar': 'حفظ إجمالي {total:.2f} كدَين على {name}؟\nالرصيد الحالي: {bal:,.2f}'},
    'saved':                {'en': 'Saved',             'ar': 'تم الحفظ'},
    'saved_msg':            {'en': 'Sale #{id} saved.\nDebt of {total:.2f} added to {name}.',
                             'ar': 'تم حفظ البيع #{id}.\nتم إضافة دَين {total:.2f} على {name}.'},
    'all_products':         {'en': 'All Products',      'ar': 'كل المنتجات'},
    'speed_products':       {'en': 'Speed Products',    'ar': 'منتجات البيع السريع'},
    'btn_add_to_speed':     {'en': '▶ Add',             'ar': '◀ إضافة'},
    'btn_rem_from_speed':   {'en': '◀ Remove',          'ar': '▶ إزالة'},
    'manage_speed_title':   {'en': 'Manage Speed Products', 'ar': 'إدارة منتجات البيع السريع'},

    # ── Products view ─────────────────────────────────────────────────────────
    'page_products':        {'en': 'Products',          'ar': 'المنتجات'},
    'search_prod':          {'en': '  Search by name or barcode…',
                             'ar': '  ابحث بالاسم أو الباركود…'},
    'col_barcode':          {'en': 'Barcode',           'ar': 'الباركود'},
    'col_category':         {'en': 'Category',          'ar': 'الفئة'},
    'col_buy':              {'en': 'Buy Price',         'ar': 'سعر الشراء'},
    'col_sale':             {'en': 'Sale Price',        'ar': 'سعر البيع'},
    'col_margin':           {'en': 'Margin',            'ar': 'الهامش'},
    'product_details':      {'en': 'Product Details',   'ar': 'تفاصيل المنتج'},
    'field_name':           {'en': 'Name *:',           'ar': 'الاسم *:'},
    'field_barcode':        {'en': 'Barcode:',          'ar': 'الباركود:'},
    'field_category':       {'en': 'Category:',         'ar': 'الفئة:'},
    'field_qty':            {'en': 'Quantity:',         'ar': 'الكمية:'},
    'btn_add_product':      {'en': ' Add Product',      'ar': ' إضافة منتج'},
    'btn_update':           {'en': ' Update',           'ar': ' تعديل'},
    'btn_clear':            {'en': '  Clear',           'ar': '  مسح'},
    'confirm_delete':       {'en': 'Confirm Delete',    'ar': 'تأكيد الحذف'},
    'delete_confirm_msg':   {'en': 'Delete "{name}"?',  'ar': 'حذف "{name}"؟'},
    'name_required':        {'en': 'Name is required.', 'ar': 'الاسم مطلوب.'},

    # ── Inventory view ────────────────────────────────────────────────────────
    'page_inventory':       {'en': 'Inventory',         'ar': 'المخزون'},
    'search_inv':           {'en': '  Search by name or category…',
                             'ar': '  ابحث بالاسم أو الفئة…'},
    'col_min_level':        {'en': 'Min Level',         'ar': 'الحد الأدنى'},
    'col_status':           {'en': 'Status',            'ar': 'الحالة'},
    'btn_adjust':           {'en': ' Adjust',           'ar': ' تعديل'},
    'in_stock':             {'en': 'In Stock',          'ar': 'متوفر'},
    'low_stock':            {'en': 'Low Stock',         'ar': 'مخزون منخفض'},
    'out_of_stock':         {'en': 'Out of Stock',      'ar': 'نفد المخزون'},
    'adjust_stock':         {'en': 'Adjust Stock',      'ar': 'تعديل المخزون'},
    'current_qty':          {'en': 'Current Quantity:', 'ar': 'الكمية الحالية:'},
    'new_qty':              {'en': 'New Quantity:',     'ar': 'الكمية الجديدة:'},
    'min_level':            {'en': 'Min Level:',        'ar': 'الحد الأدنى:'},
    'cost_price':           {'en': 'Cost Price:',       'ar': 'سعر الشراء:'},
    'total_lbl':            {'en': 'Total:',            'ar': 'الإجمالي:'},
    'out_count':            {'en': 'Out of Stock:',     'ar': 'نفد المخزون:'},
    'low_count':            {'en': 'Low Stock:',        'ar': 'مخزون منخفض:'},

    # ── Reports view ──────────────────────────────────────────────────────────
    'page_reports':         {'en': 'Sales Reports',     'ar': 'تقارير المبيعات'},
    'from_date':            {'en': 'From:',             'ar': 'من:'},
    'to_date':              {'en': 'To:',               'ar': 'إلى:'},
    'btn_generate':         {'en': ' Generate',         'ar': ' توليد'},
    'btn_export_csv':       {'en': '📥  Export CSV',    'ar': '📥  تصدير CSV'},
    'card_total_sales':     {'en': 'Total Sales',       'ar': 'إجمالي المبيعات'},
    'card_revenue':         {'en': 'Revenue',           'ar': 'الإيرادات'},
    'card_profit':          {'en': 'Profit',            'ar': 'الربح'},
    'card_avg':             {'en': 'Avg Sale',          'ar': 'متوسط البيع'},
    'col_date':             {'en': 'Date',              'ar': 'التاريخ'},
    'col_sale_id':          {'en': 'Sale #',            'ar': 'رقم البيع'},    'col_customer':         {'en': 'Customer',          'ar': 'العميل'},
    'col_items':            {'en': 'Items',             'ar': 'عدد الأصناف'},
    'col_revenue':          {'en': 'Revenue',           'ar': 'الإيراد'},
    'col_profit':           {'en': 'Profit',            'ar': 'الربح'},
    'no_data':              {'en': 'No sales in selected period.',
                             'ar': 'لا توجد مبيعات في الفترة المحددة.'},
    'export_success':       {'en': 'Exported to {path}', 'ar': 'تم التصدير إلى {path}'},
    'export_title':         {'en': 'Export CSV',        'ar': 'تصدير CSV'},

    # ── Customers view ────────────────────────────────────────────────────────
    'page_customers':       {'en': 'Customers',         'ar': 'العملاء'},
    'search_cust':          {'en': '  Search by name or phone…',
                             'ar': '  ابحث بالاسم أو الهاتف…'},
    'btn_add':              {'en': ' Add',              'ar': ' إضافة'},
    'btn_edit':             {'en': ' Edit',             'ar': ' تعديل'},
    'btn_add_debt':         {'en': ' Add Debt',         'ar': ' إضافة دَين'},
    'btn_record_payment':   {'en': ' Record Payment',   'ar': ' تسجيل دفعة'},
    'col_phone':            {'en': 'Phone',             'ar': 'الهاتف'},
    'col_debt':             {'en': 'Debt',              'ar': 'الدَين'},
    'no_cust_selected':     {'en': 'No customer selected', 'ar': 'لم يتم اختيار عميل'},
    'debt_history':         {'en': 'Debt History',      'ar': 'سجل الديون'},
    'col_note':             {'en': 'Note',              'ar': 'ملاحظة'},
    'col_balance':          {'en': 'Balance',           'ar': 'الرصيد'},
    'total_customers':      {'en': 'Total Customers',   'ar': 'إجمالي العملاء'},
    'total_outstanding':    {'en': 'Total Outstanding', 'ar': 'إجمالي الديون'},
    'add_customer':         {'en': 'New Customer',      'ar': 'عميل جديد'},
    'edit_customer':        {'en': 'Edit Customer',     'ar': 'تعديل عميل'},
    'field_full_name':      {'en': 'Name *:',           'ar': 'الاسم الكامل *:'},
    'field_phone':          {'en': 'Phone:',            'ar': 'الهاتف:'},
    'field_address':        {'en': 'Address:',          'ar': 'العنوان:'},
    'delete_cust_msg':      {'en': 'Delete customer "{name}"?\nDebt entries will also be removed.',
                             'ar': 'حذف العميل "{name}"؟\nسيتم حذف سجلات الدَين أيضاً.'},
    'add_debt_title':       {'en': 'Add Debt',          'ar': 'إضافة دَين'},
    'record_payment_title': {'en': 'Record Payment',    'ar': 'تسجيل دفعة'},
    'field_amount':         {'en': 'Amount:',           'ar': 'المبلغ:'},
    'field_note':           {'en': 'Note:',             'ar': 'ملاحظة:'},

    # ── Suppliers view ────────────────────────────────────────────────────────
    'page_suppliers':       {'en': 'Suppliers',         'ar': 'الموردون'},
    'search_sup':           {'en': 'Search suppliers…', 'ar': 'ابحث عن مورد…'},
    'billings':             {'en': 'Billings',          'ar': 'الفواتير'},
    'btn_new_billing':      {'en': ' New Billing',      'ar': ' فاتورة جديدة'},
    'items_panel':          {'en': 'Items',             'ar': 'الأصناف'},
    'btn_add_item':         {'en': ' Add Item',         'ar': ' إضافة صنف'},
    'col_buy_price':        {'en': 'Buy Price',         'ar': 'سعر الشراء'},
    'col_sale_price':       {'en': 'Sale Price',        'ar': 'سعر البيع'},
    'col_total_cost':       {'en': 'Total Cost',        'ar': 'إجمالي التكلفة'},
    'total_cost':           {'en': 'Total Cost: ',      'ar': 'إجمالي التكلفة: '},
    'add_supplier':         {'en': 'New Supplier',      'ar': 'مورد جديد'},
    'edit_supplier':        {'en': 'Edit Supplier',     'ar': 'تعديل مورد'},
    'field_fullname':       {'en': 'Full Name *:',      'ar': 'الاسم الكامل *:'},
    'sup_name_required':    {'en': 'Supplier name is required.', 'ar': 'اسم المورد مطلوب.'},
    'new_billing':          {'en': 'New Billing',       'ar': 'فاتورة جديدة'},
    'edit_billing':         {'en': 'Edit Billing',      'ar': 'تعديل فاتورة'},
    'field_date':           {'en': 'Date:',             'ar': 'التاريخ:'},
    'add_item':             {'en': 'Add Item to Billing', 'ar': 'إضافة صنف للفاتورة'},
    'edit_item':            {'en': 'Edit Item',         'ar': 'تعديل الصنف'},
    'field_product':        {'en': 'Product *:',        'ar': 'المنتج *:'},
    'field_quantity':       {'en': 'Quantity:',         'ar': 'الكمية:'},
    'new_product':          {'en': 'New Product',       'ar': 'منتج جديد'},
    'btn_create_select':    {'en': ' Create & Select',  'ar': ' إنشاء واختيار'},
    'del_supplier_msg':     {'en': 'Delete supplier "{name}" and all their billing data?\nThis cannot be undone.',
                             'ar': 'حذف المورد "{name}" وجميع فواتيره؟\nلا يمكن التراجع عن هذا.'},
    'del_billing_msg':      {'en': 'Delete this billing order and all its items?\nStock will be reversed.',
                             'ar': 'حذف هذه الفاتورة وجميع أصنافها؟\nسيتم عكس المخزون.'},
    'del_item_msg':         {'en': 'Remove this item? Stock will be reversed.',
                             'ar': 'إزالة هذا الصنف؟ سيتم عكس المخزون.'},
    'select_product_msg':   {'en': 'Please select a product.', 'ar': 'يرجى اختيار منتج.'},
    'qty_min_msg':          {'en': 'Quantity must be at least 1.', 'ar': 'يجب أن تكون الكمية 1 على الأقل.'},

    # ── Shared dialog buttons ─────────────────────────────────────────────────
    'yes':                  {'en': 'Yes',               'ar': 'نعم'},
    'no':                   {'en': 'No',                'ar': 'لا'},
    'ok':                   {'en': 'OK',                'ar': 'موافق'},
    'cancel':               {'en': 'Cancel',            'ar': 'إلغاء'},
    'save':                 {'en': 'Save',              'ar': 'حفظ'},
    'validation':           {'en': 'Validation',        'ar': 'تحقق'},
}
