"""
All UI strings in English and Arabic.
Access via:  from utils.lang import tr
             tr('key')
"""

TRANSLATIONS = {
    # ── App / Main window ─────────────────────────────────────────────────────
    'app_title':            {'en': 'Louafi Soft - Point of Sale System',
                             'ar': 'لوافي سوفت - نظام نقطة البيع'},
    'nav_dashboard':        {'en': 'Dashboard',    'ar': 'لوحة التحكم'},
    'nav_products':         {'en': 'Products',     'ar': 'المنتجات'},
    'nav_inventory':        {'en': 'Inventory',    'ar': 'المخزون'},
    'nav_reports':          {'en': 'Reports',      'ar': 'التقارير'},
    'nav_customers':        {'en': 'Customers',    'ar': 'العملاء'},
    'nav_suppliers':        {'en': 'Suppliers',    'ar': 'الموردون'},
    'btn_refresh':          {'en': 'Refresh',      'ar': 'تحديث'},
    'status_refreshed':     {'en': 'Data refreshed ✔', 'ar': 'تم التحديث ✔'},
    'lang_switch_to_ar':    {'en': 'العربية',      'ar': 'English'},

    # ── Dashboard ─────────────────────────────────────────────────────────────
    'search_placeholder':   {'en': '  Search by name or barcode…',
                             'ar': '  ابحث بالاسم أو الباركود…'},
    'search_results':       {'en': 'Search Results',   'ar': 'نتائج البحث'},
    'speed_sale':           {'en': ' Speed Sale',      'ar': ' البيع السريع'},
    'btn_manage':           {'en': ' Manage',          'ar': ' إدارة'},
    'cart':                 {'en': 'Cart',              'ar': 'سلة المشتريات'},
    'btn_clear_cart':       {'en': 'Clear Cart',        'ar': 'تفريغ السلة'},
    'col_id':               {'en': 'ID',               'ar': 'م'},
    'col_name':             {'en': 'Name',              'ar': 'الاسم'},
    'col_price':            {'en': 'Price',             'ar': 'السعر'},
    'col_qty':              {'en': 'Qty',               'ar': 'الكمية'},
    'col_total':            {'en': 'Total',             'ar': 'الإجمالي'},
    'col_actions':          {'en': 'Actions',           'ar': 'إجراءات'},
    'order_summary':        {'en': 'Order Summary',     'ar': 'ملخص الطلب'},
    'subtotal':             {'en': 'Subtotal',          'ar': 'المجموع الجزئي'},
    'discount':             {'en': 'Discount',          'ar': 'الخصم'},
    'no_discount':          {'en': 'No discount',       'ar': 'بدون خصم'},
    'tax':                  {'en': 'Tax',               'ar': 'الضريبة'},
    'amount_paid':          {'en': 'Amount Paid',       'ar': 'المبلغ المدفوع'},
    'change':               {'en': 'Change',            'ar': 'الباقي'},
    'due':                  {'en': 'Due',               'ar': 'المتبقي'},
    'payment_method':       {'en': 'Payment Method',    'ar': 'طريقة الدفع'},
    'cash':                 {'en': 'Cash',              'ar': 'نقداً'},
    'debt_on_credit':       {'en': 'Debt / On credit',  'ar': 'دين / بالأجل'},
    'complete_sale':        {'en': 'Complete Sale',     'ar': 'إتمام البيع'},
    'hold':                 {'en': 'Hold',              'ar': 'تعليق'},
    'new_sale':             {'en': 'New Sale',          'ar': 'بيع جديد'},
    'you_save':             {'en': 'You save',          'ar': 'توفّر'},
    'incl_tax':             {'en': 'incl. tax',         'ar': 'شامل الضريبة'},
    'apply':                {'en': 'Apply',             'ar': 'تطبيق'},
    'enter_code':           {'en': 'Enter code…',       'ar': 'أدخل الكود…'},
    'resume_held':          {'en': 'Resume Held Sale',  'ar': 'استئناف البيع المعلق'},
    'customer':             {'en': 'Customer',          'ar': 'العميل'},
    'walkin':               {'en': '— Walk-in / No customer —',
                             'ar': '— زيارة عادية —'},
    'total_label':          {'en': 'Total',             'ar': 'الإجمالي'},
    'btn_accept_sale':      {'en': ' Accept Sale',      'ar': ' قبول البيع'},
    'btn_save_debt':        {'en': ' Save as Debt',     'ar': ' حفظ كدَين'},
    'btn_delete':           {'en': 'Delete',            'ar': 'حذف'},
    'reload_customers':     {'en': 'Reload customer list', 'ar': 'إعادة تحميل العملاء'},
    'outstanding_debt':     {'en': 'Outstanding debt: ', 'ar': 'دين متبقٍ: '},
    'sale_complete':        {'en': 'Sale Complete',     'ar': 'تم البيع'},
    'sale_complete_msg':    {'en': 'Sale #{id}{cust} completed.\nTotal: {total:.2f}',
                             'ar': 'تم إتمام البيع #{id}{cust}.\nالإجمالي: {total:.2f}'},
    'error':                {'en': 'Error',             'ar': 'خطأ'},
    'no_customer':          {'en': 'No Customer',       'ar': 'لا يوجد عميل'},
    'no_customer_msg':      {'en': 'Please select a customer first.',
                             'ar': 'يرجى تحديد عميل أولاً.'},
    'empty_cart':           {'en': 'Empty Cart',        'ar': 'السلة فارغة'},
    'empty_cart_msg':       {'en': 'Cart is empty.',    'ar': 'السلة فارغة.'},
    'save_as_debt':         {'en': 'Save as Debt',      'ar': 'حفظ كدَين'},
    'save_debt_q':          {'en': 'Save total {total:.2f} as debt for {name}?\nCurrent balance: {bal:,.2f}',
                             'ar': 'حفظ إجمالي {total:.2f} كدَين على {name}؟\nالرصيد الحالي: {bal:,.2f}'},
    'saved':                {'en': 'Saved',             'ar': 'تم الحفظ'},
    'saved_msg':            {'en': 'Sale #{id} saved.\nDebt of {total:.2f} added to {name}.',
                             'ar': 'تم حفظ البيع #{id}.\nتم إضافة دَين {total:.2f} على {name}.'},
    'all_products':         {'en': 'All Products',      'ar': 'كل المنتجات'},
    'speed_products':       {'en': 'Speed Products',    'ar': 'منتجات البيع السريع'},
    'btn_add_to_speed':     {'en': '▶ Add',             'ar': '◀ إضافة'},
    'btn_rem_from_speed':   {'en': '◀ Remove',          'ar': '▶ إزالة'},
    'manage_speed_title':   {'en': 'Manage Speed Products', 'ar': 'إدارة منتجات البيع السريع'},

    # ── Products view ─────────────────────────────────────────────────────────
    'page_products':        {'en': 'Products',          'ar': 'المنتجات'},
    'search_prod':          {'en': '  Search by name or barcode…',
                             'ar': '  ابحث بالاسم أو الباركود…'},
    'col_barcode':          {'en': 'Barcode',           'ar': 'الباركود'},
    'col_category':         {'en': 'Category',          'ar': 'الفئة'},
    'col_buy':              {'en': 'Buy Price',         'ar': 'سعر الشراء'},
    'col_sale':             {'en': 'Sale Price',        'ar': 'سعر البيع'},
    'col_margin':           {'en': 'Margin',            'ar': 'الهامش'},
    'product_details':      {'en': 'Product Details',   'ar': 'تفاصيل المنتج'},
    'field_name':           {'en': 'Name *:',           'ar': 'الاسم *:'},
    'field_barcode':        {'en': 'Barcode:',          'ar': 'الباركود:'},
    'field_category':       {'en': 'Category:',         'ar': 'الفئة:'},
    'field_qty':            {'en': 'Quantity:',         'ar': 'الكمية:'},
    'btn_add_product':      {'en': ' Add Product',      'ar': ' إضافة منتج'},
    'btn_update':           {'en': ' Update',           'ar': ' تعديل'},
    'btn_clear':            {'en': '  Clear',           'ar': '  مسح'},
    'confirm_delete':       {'en': 'Confirm Delete',    'ar': 'تأكيد الحذف'},
    'delete_confirm_msg':   {'en': 'Delete "{name}"?',  'ar': 'حذف "{name}"؟'},
    'name_required':        {'en': 'Name is required.', 'ar': 'الاسم مطلوب.'},

    # ── Inventory view ────────────────────────────────────────────────────────
    'page_inventory':       {'en': 'Inventory',         'ar': 'المخزون'},
    'search_inv':           {'en': '  Search by name or category…',
                             'ar': '  ابحث بالاسم أو الفئة…'},
    'col_min_level':        {'en': 'Min Level',         'ar': 'الحد الأدنى'},
    'col_status':           {'en': 'Status',            'ar': 'الحالة'},
    'btn_adjust':           {'en': ' Adjust',           'ar': ' تعديل'},
    'in_stock':             {'en': 'In Stock',          'ar': 'متوفر'},
    'low_stock':            {'en': 'Low Stock',         'ar': 'مخزون منخفض'},
    'out_of_stock':         {'en': 'Out of Stock',      'ar': 'نفد المخزون'},
    'adjust_stock':         {'en': 'Adjust Stock',      'ar': 'تعديل المخزون'},
    'current_qty':          {'en': 'Current Quantity:', 'ar': 'الكمية الحالية:'},
    'new_qty':              {'en': 'New Quantity:',     'ar': 'الكمية الجديدة:'},
    'min_level':            {'en': 'Min Level:',        'ar': 'الحد الأدنى:'},
    'cost_price':           {'en': 'Cost Price:',       'ar': 'سعر الشراء:'},
    'total_lbl':            {'en': 'Total:',            'ar': 'الإجمالي:'},
    'out_count':            {'en': 'Out of Stock:',     'ar': 'نفد المخزون:'},
    'low_count':            {'en': 'Low Stock:',        'ar': 'مخزون منخفض:'},

    # ── Reports view ──────────────────────────────────────────────────────────
    'page_reports':         {'en': 'Sales Reports',     'ar': 'تقارير المبيعات'},
    'from_date':            {'en': 'From:',             'ar': 'من:'},
    'to_date':              {'en': 'To:',               'ar': 'إلى:'},
    'btn_generate':         {'en': ' Generate',         'ar': ' توليد'},
    'btn_export_csv':       {'en': '📥  Export CSV',    'ar': '📥  تصدير CSV'},
    'card_total_sales':     {'en': 'Total Sales',       'ar': 'إجمالي المبيعات'},
    'card_revenue':         {'en': 'Revenue',           'ar': 'الإيرادات'},
    'card_profit':          {'en': 'Profit',            'ar': 'الربح'},
    'card_avg':             {'en': 'Avg Sale',          'ar': 'متوسط البيع'},
    'col_date':             {'en': 'Date',              'ar': 'التاريخ'},
    'col_sale_id':          {'en': 'Sale #',            'ar': 'رقم البيع'},    'col_customer':         {'en': 'Customer',          'ar': 'العميل'},
    'col_items':            {'en': 'Items',             'ar': 'عدد الأصناف'},
    'col_revenue':          {'en': 'Revenue',           'ar': 'الإيراد'},
    'col_profit':           {'en': 'Profit',            'ar': 'الربح'},
    'no_data':              {'en': 'No sales in selected period.',
                             'ar': 'لا توجد مبيعات في الفترة المحددة.'},
    'export_success':       {'en': 'Exported to {path}', 'ar': 'تم التصدير إلى {path}'},
    'export_title':         {'en': 'Export CSV',        'ar': 'تصدير CSV'},

    # ── Customers view ────────────────────────────────────────────────────────
    'page_customers':       {'en': 'Customers',         'ar': 'العملاء'},
    'search_cust':          {'en': '  Search by name or phone…',
                             'ar': '  ابحث بالاسم أو الهاتف…'},
    'btn_add':              {'en': ' Add',              'ar': ' إضافة'},
    'btn_edit':             {'en': ' Edit',             'ar': ' تعديل'},
    'btn_add_debt':         {'en': ' Add Debt',         'ar': ' إضافة دَين'},
    'btn_record_payment':   {'en': ' Record Payment',   'ar': ' تسجيل دفعة'},
    'col_phone':            {'en': 'Phone',             'ar': 'الهاتف'},
    'col_debt':             {'en': 'Debt',              'ar': 'الدَين'},
    'no_cust_selected':     {'en': 'No customer selected', 'ar': 'لم يتم اختيار عميل'},
    'debt_history':         {'en': 'Debt History',      'ar': 'سجل الديون'},
    'col_note':             {'en': 'Note',              'ar': 'ملاحظة'},
    'col_balance':          {'en': 'Balance',           'ar': 'الرصيد'},
    'total_customers':      {'en': 'Total Customers',   'ar': 'إجمالي العملاء'},
    'total_outstanding':    {'en': 'Total Outstanding', 'ar': 'إجمالي الديون'},
    'add_customer':         {'en': 'New Customer',      'ar': 'عميل جديد'},
    'edit_customer':        {'en': 'Edit Customer',     'ar': 'تعديل عميل'},
    'field_full_name':      {'en': 'Name *:',           'ar': 'الاسم الكامل *:'},
    'field_phone':          {'en': 'Phone:',            'ar': 'الهاتف:'},
    'field_address':        {'en': 'Address:',          'ar': 'العنوان:'},
    'delete_cust_msg':      {'en': 'Delete customer "{name}"?\nDebt entries will also be removed.',
                             'ar': 'حذف العميل "{name}"؟\nسيتم حذف سجلات الدَين أيضاً.'},
    'add_debt_title':       {'en': 'Add Debt',          'ar': 'إضافة دَين'},
    'record_payment_title': {'en': 'Record Payment',    'ar': 'تسجيل دفعة'},
    'field_amount':         {'en': 'Amount:',           'ar': 'المبلغ:'},
    'field_note':           {'en': 'Note:',             'ar': 'ملاحظة:'},

    # ── Suppliers view ────────────────────────────────────────────────────────
    'page_suppliers':       {'en': 'Suppliers',         'ar': 'الموردون'},
    'search_sup':           {'en': 'Search suppliers…', 'ar': 'ابحث عن مورد…'},
    'billings':             {'en': 'Billings',          'ar': 'الفواتير'},
    'btn_new_billing':      {'en': ' New Billing',      'ar': ' فاتورة جديدة'},
    'items_panel':          {'en': 'Items',             'ar': 'الأصناف'},
    'btn_add_item':         {'en': ' Add Item',         'ar': ' إضافة صنف'},
    'col_buy_price':        {'en': 'Buy Price',         'ar': 'سعر الشراء'},
    'col_sale_price':       {'en': 'Sale Price',        'ar': 'سعر البيع'},
    'col_total_cost':       {'en': 'Total Cost',        'ar': 'إجمالي التكلفة'},
    'total_cost':           {'en': 'Total Cost: ',      'ar': 'إجمالي التكلفة: '},
    'add_supplier':         {'en': 'New Supplier',      'ar': 'مورد جديد'},
    'edit_supplier':        {'en': 'Edit Supplier',     'ar': 'تعديل مورد'},
    'field_fullname':       {'en': 'Full Name *:',      'ar': 'الاسم الكامل *:'},
    'sup_name_required':    {'en': 'Supplier name is required.', 'ar': 'اسم المورد مطلوب.'},
    'new_billing':          {'en': 'New Billing',       'ar': 'فاتورة جديدة'},
    'edit_billing':         {'en': 'Edit Billing',      'ar': 'تعديل فاتورة'},
    'field_date':           {'en': 'Date:',             'ar': 'التاريخ:'},
    'add_item':             {'en': 'Add Item to Billing', 'ar': 'إضافة صنف للفاتورة'},
    'edit_item':            {'en': 'Edit Item',         'ar': 'تعديل الصنف'},
    'field_product':        {'en': 'Product *:',        'ar': 'المنتج *:'},
    'field_quantity':       {'en': 'Quantity:',         'ar': 'الكمية:'},
    'new_product':          {'en': 'New Product',       'ar': 'منتج جديد'},
    'btn_create_select':    {'en': ' Create & Select',  'ar': ' إنشاء واختيار'},
    'del_supplier_msg':     {'en': 'Delete supplier "{name}" and all their billing data?\nThis cannot be undone.',
                             'ar': 'حذف المورد "{name}" وجميع فواتيره؟\nلا يمكن التراجع عن هذا.'},
    'del_billing_msg':      {'en': 'Delete this billing order and all its items?\nStock will be reversed.',
                             'ar': 'حذف هذه الفاتورة وجميع أصنافها؟\nسيتم عكس المخزون.'},
    'del_item_msg':         {'en': 'Remove this item? Stock will be reversed.',
                             'ar': 'إزالة هذا الصنف؟ سيتم عكس المخزون.'},
    'select_product_msg':   {'en': 'Please select a product.', 'ar': 'يرجى اختيار منتج.'},
    'qty_min_msg':          {'en': 'Quantity must be at least 1.', 'ar': 'يجب أن تكون الكمية 1 على الأقل.'},

    # ── Shared dialog buttons ─────────────────────────────────────────────────
    'yes':                  {'en': 'Yes',               'ar': 'نعم'},
    'no':                   {'en': 'No',                'ar': 'لا'},
    'ok':                   {'en': 'OK',                'ar': 'موافق'},
    'cancel':               {'en': 'Cancel',            'ar': 'إلغاء'},
    'save':                 {'en': 'Save',              'ar': 'حفظ'},
    'validation':           {'en': 'Validation',        'ar': 'تحقق'},
    'add':                  {'en': 'Add',               'ar': 'إضافة'},
    'edit':                 {'en': 'Edit',              'ar': 'تعديل'},
    'delete':               {'en': 'Delete',            'ar': 'حذف'},
    'refresh':              {'en': 'Refresh',           'ar': 'تحديث'},
    'search':               {'en': 'Search',            'ar': 'بحث'},
    'filter':               {'en': 'Filter',            'ar': 'تصفية'},
    'all':                  {'en': 'All',               'ar': 'الكل'},
    'active':               {'en': 'Active',            'ar': 'نشط'},
    'inactive':             {'en': 'Inactive',          'ar': 'غير نشط'},
    'success':              {'en': 'Success',           'ar': 'نجاح'},
    'warning':              {'en': 'Warning',           'ar': 'تحذير'},
    'confirm_action':       {'en': 'Confirm Action',    'ar': 'تأكيد الإجراء'},
    'confirm_delete':       {'en': 'Are you sure you want to delete this?',
                             'ar': 'هل أنت متأكد من الحذف؟'},

    # ── Login / Auth ──────────────────────────────────────────────────────────
    'login':                {'en': 'Login',             'ar': 'تسجيل الدخول'},
    'logout':               {'en': 'Logout',            'ar': 'تسجيل الخروج'},
    'username':             {'en': 'Username',          'ar': 'اسم المستخدم'},
    'password':             {'en': 'Password',          'ar': 'كلمة المرور'},
    'change_password':      {'en': 'Change Password',   'ar': 'تغيير كلمة المرور'},
    'old_password':         {'en': 'Current Password',  'ar': 'كلمة المرور الحالية'},
    'new_password':         {'en': 'New Password',      'ar': 'كلمة المرور الجديدة'},
    'confirm_password':     {'en': 'Confirm Password',  'ar': 'تأكيد كلمة المرور'},
    'must_change_password': {'en': 'You must change your password before continuing.',
                             'ar': 'يجب تغيير كلمة المرور قبل المتابعة.'},
    'activation':           {'en': 'Software Activation', 'ar': 'تفعيل البرنامج'},
    'activation_desc':      {'en': 'Enter your license key to activate LouafiPOS.',
                             'ar': 'أدخل مفتاح الترخيص لتفعيل نظام الوافي POS.'},
    'license_key':          {'en': 'License Key',       'ar': 'مفتاح الترخيص'},
    'activate':             {'en': 'Activate',          'ar': 'تفعيل'},
    'license_expiry_warning': {'en': 'License expires in {days} days',
                               'ar': 'سينتهي الترخيص خلال {days} أيام'},
    'sign_in_tagline':      {'en': 'Sign in to continue', 'ar': 'سجّل الدخول للمتابعة'},
    'enter_credentials':    {'en': 'Please enter username and password',
                             'ar': 'يرجى إدخال اسم المستخدم وكلمة المرور'},
    'pw_no_match':          {'en': 'Passwords do not match', 'ar': 'كلمتا المرور غير متطابقتين'},

    # ── Main window chrome ────────────────────────────────────────────────────
    # ── Hidden system dashboard ───────────────────────────────────────────────
    'hd_title':             {'en': '⚙  System Dashboard',   'ar': '⚙  لوحة النظام'},
    'hd_subtitle':          {'en': 'Admin-only · Live statistics and system diagnostics',
                             'ar': 'للمسؤول فقط · إحصائيات مباشرة وتشخيص النظام'},
    'hd_refresh':           {'en': '↻  Refresh',            'ar': '↻  تحديث'},
    'hd_updated':           {'en': 'Updated: ',             'ar': 'آخر تحديث: '},
    'hd_license':           {'en': '🔑  License',           'ar': '🔑  الترخيص'},
    'hd_sales_overview':    {'en': '📊  Sales Overview',    'ar': '📊  نظرة عامة على المبيعات'},
    'hd_recent_sales':      {'en': '🧾  Recent Sales',      'ar': '🧾  آخر المبيعات'},
    'hd_system_info':       {'en': '🖥  System Info',       'ar': '🖥  معلومات النظام'},
    'hd_lic_status':        {'en': 'Status',                'ar': 'الحالة'},
    'hd_lic_store':         {'en': 'Store ID',              'ar': 'رمز المتجر'},
    'hd_lic_expiry':        {'en': 'Expiry',                'ar': 'تاريخ الانتهاء'},
    'hd_lic_days':          {'en': 'Days Left',             'ar': 'الأيام المتبقية'},
    'hd_lic_fp':            {'en': 'Fingerprint',           'ar': 'بصمة الجهاز'},
    'hd_lic_valid':         {'en': '✅ Active',             'ar': '✅ مفعّل'},
    'hd_lic_invalid':       {'en': '❌ Invalid',            'ar': '❌ غير صالح'},
    'hd_sales_today':       {'en': 'Sales Today',           'ar': 'مبيعات اليوم'},
    'hd_rev_today':         {'en': 'Revenue Today (DA)',    'ar': 'إيرادات اليوم (د.ج)'},
    'hd_rev_month':         {'en': 'Revenue This Month',   'ar': 'إيرادات الشهر'},
    'hd_exp_month':         {'en': 'Expenses This Month',  'ar': 'مصاريف الشهر'},
    'hd_products':          {'en': 'Active Products',      'ar': 'المنتجات النشطة'},
    'hd_low_stock':         {'en': 'Low Stock Items',      'ar': 'منتجات نقص المخزون'},
    'hd_customers':         {'en': 'Customers',            'ar': 'العملاء'},
    'hd_discounts':         {'en': 'Active Discounts',     'ar': 'الخصومات النشطة'},
    'hd_col_sale':          {'en': 'Sale #',               'ar': 'رقم البيع'},
    'hd_col_datetime':      {'en': 'Date & Time',          'ar': 'التاريخ والوقت'},
    'hd_col_total':         {'en': 'Total (DA)',            'ar': 'الإجمالي (د.ج)'},
    'hd_col_cashier':       {'en': 'Cashier',              'ar': 'الصراف'},
    'hd_sys_python':        {'en': 'Python',               'ar': 'بايثون'},
    'hd_sys_platform':      {'en': 'Platform',             'ar': 'نظام التشغيل'},
    'hd_sys_machine':       {'en': 'Machine',              'ar': 'نوع المعالج'},
    'hd_sys_db':            {'en': 'DB Path',              'ar': 'مسار قاعدة البيانات'},
    'hd_sys_total_sales':   {'en': 'Total Sales (all time)', 'ar': 'إجمالي المبيعات (كل الأوقات)'},
    'hd_sys_users':         {'en': 'Users',                'ar': 'المستخدمون'},

    'app_banner':           {'en': 'Louafi Soft  ·  Point of Sale',
                             'ar': 'الوافي سوفت  ·  نظام نقطة البيع'},
    'status_ready':         {'en': 'Ready',             'ar': 'جاهز'},
    'collapse_sidebar':     {'en': 'Collapse sidebar',  'ar': 'طيّ القائمة'},
    'expand_sidebar':       {'en': 'Expand sidebar',    'ar': 'توسيع القائمة'},

    # ── Nav: new sections ─────────────────────────────────────────────────────
    'nav_sales':            {'en': 'Sales',             'ar': 'المبيعات'},
    'nav_expenses':         {'en': 'Expenses',          'ar': 'المصاريف'},
    'nav_discounts':        {'en': 'Discounts',         'ar': 'الخصومات'},
    'nav_settings':         {'en': 'Settings',          'ar': 'الإعدادات'},
    'nav_users':            {'en': 'Users',             'ar': 'المستخدمون'},

    # ── Expenses view ─────────────────────────────────────────────────────────
    'expenses':             {'en': 'Expenses',          'ar': 'المصاريف'},
    'expense_category':     {'en': 'Category',          'ar': 'الفئة'},
    'description':          {'en': 'Description',       'ar': 'الوصف'},
    'amount':               {'en': 'Amount',            'ar': 'المبلغ'},
    'paid_by':              {'en': 'Paid By',           'ar': 'دفع من قِبَل'},
    'total':                {'en': 'Total',             'ar': 'الإجمالي'},
    'date_from':            {'en': 'From',              'ar': 'من'},
    'date_to':              {'en': 'To',                'ar': 'إلى'},

    # ── Discounts view ────────────────────────────────────────────────────────
    'discounts':            {'en': 'Discounts',         'ar': 'الخصومات'},
    'discount_name':        {'en': 'Name',              'ar': 'الاسم'},
    'discount_type':        {'en': 'Type',              'ar': 'النوع'},
    'percentage':           {'en': 'Percentage',        'ar': 'نسبة مئوية'},
    'fixed':                {'en': 'Fixed Amount',      'ar': 'مبلغ ثابت'},
    'coupon':               {'en': 'Coupon',            'ar': 'كوبون'},
    'value':                {'en': 'Value',             'ar': 'القيمة'},
    'coupon_code':          {'en': 'Coupon Code',       'ar': 'كود الخصم'},
    'min_purchase':         {'en': 'Min Purchase',      'ar': 'الحد الأدنى للشراء'},
    'valid_from':           {'en': 'Valid From',        'ar': 'صالح من'},
    'valid_to':             {'en': 'Valid To',          'ar': 'صالح حتى'},

    # ── Settings view ─────────────────────────────────────────────────────────
    'settings':             {'en': 'Settings',          'ar': 'الإعدادات'},
    'store_name':           {'en': 'Store Name',        'ar': 'اسم المتجر'},
    'address':              {'en': 'Address',           'ar': 'العنوان'},
    'phone':                {'en': 'Phone',             'ar': 'الهاتف'},
    'currency':             {'en': 'Currency',          'ar': 'العملة'},
    'tax_rate':             {'en': 'Tax Rate',          'ar': 'نسبة الضريبة'},
    'language':             {'en': 'Language',          'ar': 'اللغة'},
    'theme':                {'en': 'Theme',             'ar': 'المظهر'},
    'light':                {'en': 'Light',             'ar': 'فاتح'},
    'dark':                 {'en': 'Dark',              'ar': 'داكن'},
    'receipt_header':       {'en': 'Receipt Header',    'ar': 'ترويسة الإيصال'},
    'receipt_footer':       {'en': 'Receipt Footer',    'ar': 'ذيل الإيصال'},
    'loyalty_rate':         {'en': 'Loyalty Rate',      'ar': 'معدل نقاط الولاء'},
    'backup_interval':      {'en': 'Backup Interval',   'ar': 'فترة النسخ الاحتياطي'},
    'backup_destination':   {'en': 'Backup Destination', 'ar': 'مسار النسخ الاحتياطي'},
    'inactivity_timeout':   {'en': 'Inactivity Timeout', 'ar': 'مهلة الخمول'},
    'create_backup':        {'en': 'Create Backup',     'ar': 'إنشاء نسخة احتياطية'},
    'restore_backup':       {'en': 'Restore Backup',    'ar': 'استعادة نسخة احتياطية'},

    # ── User management view ──────────────────────────────────────────────────
    'users':                {'en': 'Users',             'ar': 'المستخدمون'},
    'users_subtitle':       {'en': 'Manage system accounts and access roles',
                             'ar': 'إدارة حسابات النظام وصلاحيات الوصول'},
    'create_user':          {'en': 'Create User',       'ar': 'إنشاء مستخدم'},
    'new_user':             {'en': 'New User',          'ar': 'مستخدم جديد'},
    'edit_user':            {'en': 'Edit User',         'ar': 'تعديل مستخدم'},
    'full_name':            {'en': 'Full Name',         'ar': 'الاسم الكامل'},
    'role':                 {'en': 'Role',              'ar': 'الصلاحية'},
    'status':               {'en': 'Status',            'ar': 'الحالة'},
    'admin':                {'en': 'Admin',             'ar': 'مدير'},
    'supervisor':           {'en': 'Supervisor',        'ar': 'مشرف'},
    'cashier':              {'en': 'Cashier',           'ar': 'صراف'},
    'reset_password':       {'en': 'Reset Password',    'ar': 'إعادة تعيين كلمة المرور'},
    'toggle_active':        {'en': 'Toggle Active',     'ar': 'تبديل التفعيل'},
    'col_last_login':       {'en': 'Last Login',        'ar': 'آخر دخول'},
    'col_must_change_pw':   {'en': 'Must Change PW',    'ar': 'تغيير كلمة المرور'},
    'never':                {'en': 'Never',             'ar': 'لم يسجل بعد'},
    'admin_only':           {'en': 'Admin only',        'ar': 'للمديرين فقط'},
    'edit_product':         {'en': 'Edit',              'ar': 'تعديل'},
    'image':                {'en': 'Logo/Image',        'ar': 'الشعار'},

    # ── Discounts view (extra keys) ───────────────────────────────────────────
    'new_discount':         {'en': 'New Discount',      'ar': 'خصم جديد'},
    'edit_discount':        {'en': 'Edit Discount',     'ar': 'تعديل خصم'},
    'discounts_subtitle':   {'en': 'Manage promotions, coupons and special offers',
                             'ar': 'إدارة العروض والكوبونات والخصومات الخاصة'},
    'active_only':          {'en': 'Active only',       'ar': 'النشطة فقط'},

    # ── Expenses view (extra keys) ────────────────────────────────────────────
    'new_expense':          {'en': 'New Expense',       'ar': 'مصروف جديد'},
    'edit_expense':         {'en': 'Edit Expense',      'ar': 'تعديل مصروف'},
    'expenses_subtitle':    {'en': 'Track and manage all store expenses',
                             'ar': 'تتبع وإدارة مصاريف المتجر'},
    'insuf_perms':          {'en': 'Insufficient permissions', 'ar': 'صلاحيات غير كافية'},

    # ── Settings view (extra keys) ────────────────────────────────────────────
    'settings_subtitle':    {'en': 'Configure store, app, and backup preferences',
                             'ar': 'إعداد بيانات المتجر والتطبيق والنسخ الاحتياطي'},
    'tab_store':            {'en': 'Store',             'ar': 'المتجر'},
    'tab_receipt':          {'en': 'Receipt',           'ar': 'الإيصال'},
    'tab_app':              {'en': 'App',               'ar': 'التطبيق'},
    'tab_backup':           {'en': 'Backup',            'ar': 'النسخ الاحتياطي'},
    'font_size':            {'en': 'Font Size',         'ar': 'حجم الخط'},
    'existing_backups':     {'en': 'Existing Backups',  'ar': 'النسخ الاحتياطية الموجودة'},

    # ── Returns & Refunds ──────────────────────────────────────────────────────
    'ret_title':            {'en': 'Returns & Refunds',  'ar': 'المرتجعات والمسترجعات'},
    'ret_open':             {'en': 'Return / Refund',    'ar': 'مرتجع / استرجاع'},
    'ret_search_ph':        {'en': 'Invoice #, customer name or phone…',
                             'ar': 'رقم الفاتورة أو اسم العميل أو الهاتف…'},
    'ret_confirm':          {'en': 'Confirm Return',     'ar': 'تأكيد المرتجع'},
    'ret_reason':           {'en': 'Reason (optional)',  'ar': 'السبب (اختياري)'},
    'ret_reason_ph':        {'en': 'e.g. wrong item, damaged, customer changed mind…',
                             'ar': 'مثال: منتج خاطئ، تالف، غير مرغوب فيه…'},
    'ret_total_refund':     {'en': 'Total Refund',       'ar': 'إجمالي المسترجع'},
    'ret_select_sale':      {'en': 'Please select an invoice first.',
                             'ar': 'يرجى اختيار فاتورة أولاً.'},
    'ret_no_items':         {'en': 'No returnable items on this invoice.',
                             'ar': 'لا توجد أصناف قابلة للإرجاع في هذه الفاتورة.'},
    'ret_qty_error':        {'en': 'Return quantity cannot exceed the remaining quantity.',
                             'ar': 'كمية الإرجاع لا يمكن أن تتجاوز الكمية المتبقية.'},
    'ret_success_title':    {'en': 'Return Completed',   'ar': 'تم إتمام المرتجع'},
    'ret_success_msg':      {'en': 'Return #{id} recorded.\nRefund: {amount} {cur}\nStock has been restored.',
                             'ar': 'تم تسجيل المرتجع #{id}.\nالمسترجع: {amount} {cur}\nتمت إعادة المنتجات للمخزون.'},
    'ret_fully_returned':   {'en': 'Returned',           'ar': 'مسترجع'},
    'ret_no_results':       {'en': 'No matching sales found.',
                             'ar': 'لا توجد مبيعات مطابقة.'},
    'st_completed':         {'en': 'Completed',          'ar': 'مكتمل'},
    'st_partial':           {'en': 'Partial',            'ar': 'جزئي'},
    'col_invoice':          {'en': 'Invoice #',          'ar': 'رقم الفاتورة'},
    'col_payment':          {'en': 'Payment',            'ar': 'الدفع'},
    'col_product':          {'en': 'Product',            'ar': 'المنتج'},
    'col_sold':             {'en': 'Sold',               'ar': 'المباع'},
    'col_returned':         {'en': 'Returned',           'ar': 'المسترجع'},
    'col_return_qty':       {'en': 'To Return',          'ar': 'للإرجاع'},
    'col_unit_price':       {'en': 'Unit Price',         'ar': 'سعر الوحدة'},
    'col_refund':           {'en': 'Refund',             'ar': 'المبلغ المسترجع'},
    'ret_refunded_total':   {'en': 'Refunded',           'ar': 'المسترجع'},
}
